use serde::{Deserialize, Serialize};

use crate::types::shared::{ImageDetail, ImageUrl};

use super::cache_control::CacheControl;

/// Text content that can appear in a chat message.
///
/// Providers translate this semantic text block to their native content-part
/// representation. Attach [`CacheControl`] when a provider should treat this
/// block as a prompt-cache boundary.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct TextPart {
    /// UTF-8 text sent to or returned from the model.
    pub text: String,
    /// Optional prompt-cache behavior for this content block.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

impl TextPart {
    /// Creates a text part without cache-control metadata.
    pub fn new(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            cache_control: None,
        }
    }

    /// Returns this text part with cache-control metadata attached.
    pub fn with_cache_control(mut self, cache_control: CacheControl) -> Self {
        self.cache_control = Some(cache_control);
        self
    }
}

/// Assistant refusal content returned or replayed as a structured part.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct RefusalPart {
    /// Refusal text generated by the model.
    pub refusal: String,
}

impl RefusalPart {
    /// Creates a refusal content part.
    pub fn new(refusal: impl Into<String>) -> Self {
        Self {
            refusal: refusal.into(),
        }
    }
}

/// Image content that can appear in a user message.
///
/// The image source is provider-neutral. Providers decide whether URLs, data
/// URIs, uploaded file handles, or storage URIs are supported for a selected
/// model.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct ImagePart {
    /// Image URL, data URI, or provider-supported file URI plus detail hint.
    pub image: ImageUrl,
    /// Optional prompt-cache behavior for this content block.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

impl ImagePart {
    /// Creates an image part from a URL, data URI, or provider-supported URI.
    pub fn from_url(url: impl Into<String>) -> Self {
        Self {
            image: ImageUrl {
                url: url.into(),
                detail: Default::default(),
            },
            cache_control: None,
        }
    }

    /// Returns this image part with a media detail hint.
    pub fn with_detail(mut self, detail: ImageDetail) -> Self {
        self.image.detail = Some(detail);
        self
    }

    /// Returns this image part with cache-control metadata attached.
    pub fn with_cache_control(mut self, cache_control: CacheControl) -> Self {
        self.cache_control = Some(cache_control);
        self
    }
}

/// Audio encoding for input audio content.
#[derive(Debug, Serialize, Deserialize, Default, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum InputAudioFormat {
    /// Waveform audio.
    Wav,
    /// MPEG layer 3 audio.
    #[default]
    Mp3,
}

/// Input audio bytes supplied to a multimodal chat model.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct InputAudio {
    /// Base64-encoded audio data.
    pub data: String,
    /// Encoding format for [`InputAudio::data`].
    pub format: InputAudioFormat,
}

/// Audio content that can appear in a user message.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct AudioPart {
    /// Encoded audio input.
    pub input_audio: InputAudio,
}

/// Typed video metadata for file-like media inputs.
///
/// Providers that support video inputs translate these fields to their native
/// names. Unknown provider-native metadata belongs in `provider_options`, not
/// in this public chat type.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct VideoMetadata {
    /// Frames per second hint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fps: Option<f32>,
    /// Start offset, using the provider's accepted duration string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_offset: Option<String>,
    /// End offset, using the provider's accepted duration string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_offset: Option<String>,
}

/// File, document, image, or video content supplied to a chat model.
///
/// At least one of [`FileInput::data`] or [`FileInput::id`] must be present for
/// providers that support file inputs. Providers report a transform error when
/// the selected provider cannot route the supplied source.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct FileInput {
    /// Inline file data, usually a data URI or raw base64 with a media type.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// Provider file id or provider-supported file URI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Optional display filename.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// Optional MIME type such as `application/pdf` or `video/mp4`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
    /// Optional media detail hint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<ImageDetail>,
    /// Optional typed metadata for video inputs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_metadata: Option<VideoMetadata>,
}

/// File content that can appear in a user message.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct FilePart {
    /// File source and media metadata.
    pub file: FileInput,
    /// Optional prompt-cache behavior for this content block.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}
