use derive_builder::Builder;
use serde::{Deserialize, Serialize};

use crate::error::SigmaError;
use crate::types::shared::{ImageDetail, ImageUrl};

use super::cache_control::CacheControl;

#[derive(Debug, Serialize, Deserialize, Default, Clone, Builder, PartialEq)]
#[builder(name = "ChatCompletionRequestMessageContentPartTextArgs")]
#[builder(pattern = "mutable")]
#[builder(setter(into, strip_option), default)]
#[builder(derive(Debug))]
#[builder(build_fn(error = "SigmaError"))]
pub struct ChatCompletionRequestMessageContentPartText {
    pub text: String,
    /// Provider cache-control metadata for this content block.
    ///
    /// Providers translate this semantic hint to their native cache-control
    /// shape when supported. OpenAI-compatible providers serialize it as part
    /// of the content block. Use array content parts when a text message needs
    /// cache-control metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct ChatCompletionRequestMessageContentPartRefusal {
    /// The refusal message generated by the model.
    pub refusal: String,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, Builder, PartialEq)]
#[builder(name = "ChatCompletionRequestMessageContentPartImageArgs")]
#[builder(pattern = "mutable")]
#[builder(setter(into, strip_option), default)]
#[builder(derive(Debug))]
#[builder(build_fn(error = "SigmaError"))]
pub struct ChatCompletionRequestMessageContentPartImage {
    pub image_url: ImageUrl,
    /// Provider cache-control metadata for this content block.
    ///
    /// Providers translate this semantic hint to their native cache-control
    /// shape when supported. OpenAI-compatible providers serialize it as part
    /// of the content block.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum InputAudioFormat {
    Wav,
    #[default]
    Mp3,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct InputAudio {
    /// Base64 encoded audio data.
    pub data: String,
    /// The format of the encoded audio data. Currently supports "wav" and "mp3".
    pub format: InputAudioFormat,
}

/// Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
#[derive(Debug, Serialize, Deserialize, Default, Clone, Builder, PartialEq)]
#[builder(name = "ChatCompletionRequestMessageContentPartAudioArgs")]
#[builder(pattern = "mutable")]
#[builder(setter(into, strip_option), default)]
#[builder(derive(Debug))]
#[builder(build_fn(error = "SigmaError"))]
pub struct ChatCompletionRequestMessageContentPartAudio {
    pub input_audio: InputAudio,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct FileObject {
    /// The base64 encoded file data, used when passing the file to the model
    /// as a string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_data: Option<String>,
    /// The ID of an uploaded file to use as input.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// The name of the file, used when passing the file to the model as a
    /// string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// Optional MIME type used by providers that need explicit media typing.
    ///
    /// Gemini uses this to build `inlineData` or `fileData` parts. When this is
    /// omitted for inline base64 data, sigma attempts to infer the MIME type
    /// from a data URI and otherwise returns a provider transform error.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// Optional provider media resolution hint for document, image, or video
    /// inputs.
    ///
    /// Gemini maps this to `mediaResolution` on a part or generation config
    /// depending on model capability.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<ImageDetail>,
    /// Optional Gemini video metadata for file inputs.
    ///
    /// Values are forwarded as provider-native JSON after converting common
    /// snake_case keys such as `start_offset` and `end_offset` to Gemini's
    /// camelCase field names.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_metadata: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct ChatCompletionRequestMessageContentPartFile {
    pub file: FileObject,
    /// Provider cache-control metadata for this content block.
    ///
    /// Providers translate this semantic hint to their native cache-control
    /// shape when supported. OpenAI-compatible providers serialize it as part
    /// of the content block.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}
