use serde::{Deserialize, Serialize};

use crate::types::chat::messages::{ReasoningBlock, Role};
use crate::types::chat::options::ServiceTier;
use crate::types::chat::response::{ChoiceLogprobs, FinishReason, Usage};

/// Partial function call data in a streamed tool-call delta.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
pub struct FunctionCallDelta {
    /// Function name when first announced.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Partial JSON argument text.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

/// Kind of streamed tool call.
#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ToolCallKind {
    /// Function tool call.
    Function,
}

/// Tool-call delta in a streamed chat response.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ToolCallDelta {
    /// Tool call index within the choice.
    pub index: u32,
    /// Tool call id when announced.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Tool call kind when announced.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<ToolCallKind>,
    /// Partial function call data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<FunctionCallDelta>,
    /// Reasoning signatures or blocks associated with this tool call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Vec<ReasoningBlock>>,
}

/// Assistant delta generated by a streamed model response.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AssistantDelta {
    /// Text content delta.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Reasoning blocks or signatures in this delta.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Vec<ReasoningBlock>>,
    /// Tool-call deltas.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCallDelta>>,
    /// Role when the provider announces one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// Refusal text delta.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refusal: Option<String>,
}

/// One streamed choice in a chat stream chunk.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatStreamChoice {
    /// Choice index.
    pub index: u32,
    /// Assistant delta.
    pub delta: AssistantDelta,
    /// Finish reason when this chunk closes a choice.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<FinishReason>,
    /// Token log probability details.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChoiceLogprobs>,
}

/// Streamed chat response chunk returned by sigma.
#[derive(Debug, Deserialize, Clone, PartialEq, Serialize)]
pub struct ChatStreamChunk {
    /// Provider response id.
    pub id: String,
    /// Streamed choices.
    pub choices: Vec<ChatStreamChoice>,
    /// Unix timestamp supplied by the provider or synthesized by sigma.
    pub created: u32,
    /// Provider model that handled the request.
    pub model: String,
    /// Service tier used by the provider when reported.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
    /// Stream chunk object type.
    pub object: String,
    /// Usage when included in the stream.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}
