use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;

use crate::types::chat::messages::ReasoningBlock;
use crate::types::shared::{CustomGrammarFormatParam, FunctionCall, FunctionName, FunctionObject};

/// Tool call emitted by an assistant message.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolCall {
    /// Function tool call with JSON arguments encoded as a string.
    Function(FunctionToolCall),
    /// Custom text or grammar tool call.
    Custom(CustomToolCall),
}

impl From<FunctionToolCall> for ToolCall {
    fn from(value: FunctionToolCall) -> Self {
        Self::Function(value)
    }
}

impl From<CustomToolCall> for ToolCall {
    fn from(value: CustomToolCall) -> Self {
        Self::Custom(value)
    }
}

/// Function tool call emitted by the model.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct FunctionToolCall {
    /// Tool call identifier.
    pub id: String,
    /// Function name and JSON arguments generated by the model.
    pub function: FunctionCall,
    /// Reasoning signatures or blocks that must travel with this call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Vec<ReasoningBlock>>,
}

/// Custom tool call emitted by the model.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct CustomToolCall {
    /// Tool call identifier.
    pub id: String,
    /// Custom tool name and generated input.
    pub custom_tool: CustomToolCallInput,
    /// Reasoning signatures or blocks that must travel with this call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Vec<ReasoningBlock>>,
}

/// Input generated for a custom tool call.
#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct CustomToolCallInput {
    /// Custom tool name.
    pub name: String,
    /// Custom tool input text.
    pub input: String,
}

/// Tool definition made available to a chat model.
#[derive(Clone, Serialize, Debug, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolDefinition {
    /// Function tool with a JSON-schema parameter contract.
    Function(FunctionTool),
    /// Custom text or grammar tool.
    Custom(CustomToolDefinition),
}

impl ToolDefinition {
    /// Creates a function tool definition.
    pub fn function(function: FunctionObject) -> Self {
        Self::Function(FunctionTool { function })
    }
}

/// Function tool definition.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct FunctionTool {
    /// Function contract exposed to the model.
    pub function: FunctionObject,
}

/// Custom tool definition.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct CustomToolDefinition {
    /// Custom tool metadata and input format.
    pub custom: CustomToolProperties,
}

/// Properties for a custom tool definition.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct CustomToolProperties {
    /// Custom tool name.
    pub name: String,
    /// Optional model-facing description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Custom tool input format.
    pub format: CustomToolFormat,
}

/// Input format for a custom tool.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CustomToolFormat {
    /// Unconstrained free-form text.
    #[default]
    Text,
    /// Grammar-constrained input.
    Grammar {
        /// Grammar syntax and definition.
        grammar: CustomGrammarFormatParam,
    },
}

/// A named function tool choice.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct NamedFunctionToolChoice {
    /// Function name to force.
    pub function: FunctionName,
}

impl From<&str> for NamedFunctionToolChoice {
    fn from(value: &str) -> Self {
        Self {
            function: FunctionName {
                name: value.to_string(),
            },
        }
    }
}

impl From<String> for NamedFunctionToolChoice {
    fn from(value: String) -> Self {
        Self {
            function: FunctionName { name: value },
        }
    }
}

/// A named custom tool choice.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct NamedCustomToolChoice {
    /// Custom tool name to force.
    pub custom: CustomToolName,
}

/// Custom tool name.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct CustomToolName {
    /// Custom tool name.
    pub name: String,
}

/// Controls which tool, if any, a model may call.
#[derive(Clone, Debug, PartialEq)]
pub enum ToolChoice {
    /// Restrict the available tools and mode.
    Allowed(AllowedToolsChoice),
    /// Force a named function tool.
    Function(NamedFunctionToolChoice),
    /// Force a named custom tool.
    Custom(NamedCustomToolChoice),
    /// Use a simple tool-choice mode.
    Mode(ToolChoiceMode),
}

impl Serialize for ToolChoice {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        match self {
            Self::Allowed(choice) => serialize_tagged("allowed", choice, serializer),
            Self::Function(choice) => serialize_tagged("function", choice, serializer),
            Self::Custom(choice) => serialize_tagged("custom", choice, serializer),
            Self::Mode(mode) => mode.serialize(serializer),
        }
    }
}

impl<'de> Deserialize<'de> for ToolChoice {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = Value::deserialize(deserializer)?;
        match value {
            Value::String(_) => serde_json::from_value(value)
                .map(Self::Mode)
                .map_err(D::Error::custom),
            Value::Object(mut object) => {
                let Some(tool_type) = object.remove("type").and_then(|value| match value {
                    Value::String(value) => Some(value),
                    _ => None,
                }) else {
                    return Err(D::Error::custom("tool choice object missing string type"));
                };

                match tool_type.as_str() {
                    "allowed" => serde_json::from_value(Value::Object(object))
                        .map(Self::Allowed)
                        .map_err(D::Error::custom),
                    "function" => serde_json::from_value(Value::Object(object))
                        .map(Self::Function)
                        .map_err(D::Error::custom),
                    "custom" => serde_json::from_value(Value::Object(object))
                        .map(Self::Custom)
                        .map_err(D::Error::custom),
                    "mode" => object
                        .remove("mode")
                        .ok_or_else(|| D::Error::custom("mode tool choice missing mode"))
                        .and_then(|value| {
                            serde_json::from_value(value)
                                .map(Self::Mode)
                                .map_err(D::Error::custom)
                        }),
                    "auto" | "none" | "required" => {
                        serde_json::from_value(Value::String(tool_type))
                            .map(Self::Mode)
                            .map_err(D::Error::custom)
                    }
                    other => Err(D::Error::custom(format!(
                        "unknown tool choice type `{other}`"
                    ))),
                }
            }
            _ => Err(D::Error::custom("tool choice must be a string or object")),
        }
    }
}

fn serialize_tagged<T, S>(tag: &str, value: &T, serializer: S) -> Result<S::Ok, S::Error>
where
    T: Serialize,
    S: Serializer,
{
    let mut object = match serde_json::to_value(value).map_err(serde::ser::Error::custom)? {
        Value::Object(object) => object,
        _ => {
            return Err(serde::ser::Error::custom(
                "tagged tool choice must be an object",
            ));
        }
    };
    object.insert("type".to_string(), Value::String(tag.to_string()));
    Value::Object(object).serialize(serializer)
}

impl ToolChoice {
    /// Creates an allowed-tools choice.
    pub fn allowed(choice: AllowedToolsChoice) -> Self {
        Self::Allowed(choice)
    }

    /// Creates a forced function tool choice.
    pub fn function(name: impl Into<String>) -> Self {
        Self::Function(NamedFunctionToolChoice {
            function: FunctionName { name: name.into() },
        })
    }
}

/// Allow-list and mode for tool use.
#[derive(Clone, Serialize, Default, Debug, Deserialize, PartialEq)]
pub struct AllowedToolsChoice {
    /// Tool-call mode while the allow-list is active.
    pub mode: ToolChoiceAllowedMode,
    /// Tool definitions the model may call.
    pub tools: Vec<ToolDefinition>,
}

/// Tool-choice mode for an allow-list.
#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ToolChoiceAllowedMode {
    /// Let the model decide whether to call an allowed tool.
    #[default]
    Auto,
    /// Require a call to one of the allowed tools.
    Required,
}

/// Simple tool-choice modes.
#[derive(Clone, Serialize, Debug, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ToolChoiceMode {
    /// Disable tool calls.
    #[default]
    None,
    /// Let the model decide whether to call a tool.
    Auto,
    /// Require the model to call a tool.
    Required,
}
